repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # - repo: https://github.com/MarcoGorelli/absolufy-imports
  #   rev: v0.3.1
  #   hooks:
  #     - id: absolufy-imports
  # - repo: https://github.com/charliermarsh/ruff-pre-commit
  #   # Ruff version.
  #   rev: v0.5.2
  #   hooks:
  #     - id: ruff
  #       args: [--fix, --exit-non-zero-on-fix]
  # - repo: https://github.com/psf/black-pre-commit-mirror
  #   rev: 24.4.2
  #   hooks:
  #     - id: black
