name: Test install

on: [push, workflow_dispatch]

jobs:
  minimal:
    name: Test install minimal (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: true

      - name: Test install
        run: |
          ./scripts/install.sh

      - name: Test uninstall
        run: |
          ./scripts/uninstall.sh

  minimal_no_submodule:
    name: Test install minimal without submodule (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: false

      - name: Test install
        run: |
          ./scripts/install.sh

      - name: Test uninstall
        run: |
          ./scripts/uninstall.sh

  dev_install:
    name: Test install full (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: true

      - name: Test install
        run: |
          ./scripts/install.sh --dev

      - name: Test uninstall
        run: |
          ./scripts/uninstall.sh
