name: Test install

on: [push, workflow_dispatch]

jobs:
  pipeline:

    name: pipeline ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: true

      - name: Run setup
        run: |
          ./install.sh
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            ./set_up_debian.sh
            ./set_up_debian_dev.sh --optional
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            ./macos/install.sh
            ./macos/set_defaults.sh --optional
          fi
