name: Test install

on: [push, workflow_dispatch]

jobs:
  pipeline:

    name: pipeline (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run setup
        run: |
          ./install.sh
          ./set_up_debian.sh
